# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssgw-cloud-order?characterEncoding=UTF8
    username: root
    password: 123456
  cloud:
    # 配置nacos注册中心的地址
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SH # 配置服务所属集群名称
    # 集成nacos的负载均衡算法，默认：随机
    loadbalancer:
      nacos:
        enabled: true
  application:
    name: ssgw-cloud-order
# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.shousi.ssgw.cloud.order.entity
  mapper-locations: classpath:/mapper/*.xml