# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssgw-cloud-order?characterEncoding=UTF8
    username: root
    password: 123456
  cloud:
    # 配置nacos注册中心的地址
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SH # 配置服务所属集群名称
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-rules
            namespace: dev
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    # 集成nacos的负载均衡算法，默认：随机
#    loadbalancer:
#      nacos:
#        enabled: true
    # openfeign日志级别配置
    openfeign:
      client:
        config:
#          ssgw-cloud-user: 针对于某个服务的配置
          default: # 针对于所有服务
            logger-level: full
            connect-timeout: 5000
            read-timeout: 2000
            retryer: com.shousi.ssgw.cloud.feign.FeignClientRetryer
  application:
    name: ssgw-cloud-order
# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.shousi.ssgw.cloud.entity
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.shousi.ssgw.cloud.feign: debug

feign:
  sentinel:
    enabled: true