# 配置服务端口号
server:
  port: 10100

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssgw-cloud-user?characterEncoding=UTF8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        namespace: dev
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置sentinel控制台地址
      web-context-unify: false # 配置是否使用统一web上下文
  config:
    import:
      - nacos:ssgw-cloud-user-dev.yml
  application:
    name: ssgw-cloud-user
# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.shousi.ssgw.cloud.entity
  mapper-locations: classpath:/mapper/*.xml